Esx support with possibility for qb
alberttheprince/popcornrp-customs pull request #5
Opened 2023-05-22 06:18 UTC by Sampuke

2023-05-22 06:26 UTC, Sampuke commented
I also added Config.Performance if some people have mechanic jobs which are used only for performance upgrades.

2023-05-22 06:29 UTC, alberttheprince commented
@Jorn08 please review big homie

2023-05-22 12:09 UTC, Jorn08 requested changes
I would prefer the framework specified client and server functions to be moved in their own files. e.g. `client/core.lua`, `server/core.lua`, or a single file with distinction between client and server.

2023-05-22 12:09 UTC, Jorn08 commented on server.lua
> +Functions = {}
Is there a reason this should be global?

2023-05-22 12:09 UTC, Jorn08 commented on client/menus/performance.lua
> +if not Config.Performance then return end
Already prevented by `if Config.Performance then` in main.lua#L54?

2023-05-22 12:09 UTC, Jorn08 commented on client/menus/main.lua
> +    return lib.getVehicleProperties(vehicle)
qb uses [`QBCore.Functions.SetVehicleProperties`](https://docs.qbcore.org/qbcore-documentation/qb-core/client-function-reference#qbcore.functions.setvehicleproperties)  to set the vehicle properties back, will this not break that?

2023-05-22 12:09 UTC, Jorn08 commented on client/menus/main.lua
> +local Core, corename
This is unused

2023-05-22 12:09 UTC, Jorn08 commented on client/menus/main.lua
> +    print('You arent using esx or qb, if you want payment to work use one of them.')
Making this code redundant

2023-05-30 08:17 UTC, mahanmoulaei commented on client/menus/main.lua
> +elseif GetResourceState('es_extended') == 'starter' then
There is a typo here

2023-05-30 08:17 UTC, mahanmoulaei commented on client/zones.lua
> +elseif GetResourceState('es_extended') == 'starter' then
There is a typo here

2023-05-30 08:17 UTC, mahanmoulaei commented on server.lua
> +        Functions[CoreName].RemoveMoney(player, 'bank', amount)
If I'm not mistaken, both qb and esx support reason parameter to add/remove money so you can keep it there

2023-05-30 08:17 UTC, mahanmoulaei commented on server.lua
> +    return player.getJob().name
It's a good practice to use the safe operator of `?` for nil checking to reduce code error. Same thing applies to GetBank()

2023-05-30 08:17 UTC, mahanmoulaei commented on server.lua
> +    return player.PlayerData.job.name
It's a good practice to use the safe operator of `?` for nil checking to reduce code error

2023-08-08 17:30 UTC, closed without merging